#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${1:-$ROOT_DIR/dist/moma}"
OUTPUT_DIR="$(dirname "$OUTPUT")"
MODULE_DIR="$ROOT_DIR/src/lib"
HELP_MARKDOWN="$ROOT_DIR/docs/moma-help.md"
PREVIEW_MARKDOWN="$ROOT_DIR/docs/moma-preview.md"
PREVIEW_HTML="$ROOT_DIR/preview/index.html"
PREVIEW_CSS="$ROOT_DIR/preview/styles.css"
PREVIEW_JS="$ROOT_DIR/preview/app.js"

modules=(
    10-core.sh
    20-title.sh
    30-section-message.sh
    35-simple-list.sh
    40-box-prompt.sh
    45-label.sh
    50-input.sh
    55-select.sh
    60-rabbit.sh
    70-interaction.sh
    75-system.sh
    80-preview.sh
    90-cli.sh
)

mkdir -p "$OUTPUT_DIR"
tmp_file="$(mktemp "$OUTPUT_DIR/.moma.XXXXXX")"
trap 'rm -f "$tmp_file"' EXIT

cat > "$tmp_file" <<'HEADER'
#!/usr/bin/env bash
# Generated by build.sh. Edit files in src/lib instead of this file.

MOMA_VERSION="1.4.4"
HEADER

if [[ ! -f "$HELP_MARKDOWN" ]]; then
    printf 'build: missing help document: %s\n' "$HELP_MARKDOWN" >&2
    exit 1
fi

for required_asset in "$PREVIEW_MARKDOWN" "$PREVIEW_HTML" "$PREVIEW_CSS" "$PREVIEW_JS"; do
    if [[ ! -f "$required_asset" ]]; then
        printf 'build: missing preview asset: %s\n' "$required_asset" >&2
        exit 1
    fi
done

cat >> "$tmp_file" <<'HELP_HEADER'

# embedded document: docs/moma-help.md
_moma_help_markdown () {
    cat <<'MOMA_HELP_MARKDOWN_EOF'
HELP_HEADER
cat "$HELP_MARKDOWN" >> "$tmp_file"
cat >> "$tmp_file" <<'HELP_FOOTER'
MOMA_HELP_MARKDOWN_EOF
}
HELP_FOOTER

cat >> "$tmp_file" <<'PREVIEW_MD_HEADER'

# embedded document: docs/moma-preview.md
_moma_preview_markdown_document () {
    cat <<'MOMA_PREVIEW_MARKDOWN_EOF'
PREVIEW_MD_HEADER
cat "$PREVIEW_MARKDOWN" >> "$tmp_file"
cat >> "$tmp_file" <<'PREVIEW_MD_FOOTER'
MOMA_PREVIEW_MARKDOWN_EOF
}
PREVIEW_MD_FOOTER

cat >> "$tmp_file" <<'PREVIEW_HTML_HEADER'

# embedded document: preview/index.html
_moma_preview_web_index () {
    cat <<'MOMA_PREVIEW_HTML_EOF'
PREVIEW_HTML_HEADER
cat "$PREVIEW_HTML" >> "$tmp_file"
cat >> "$tmp_file" <<'PREVIEW_HTML_FOOTER'
MOMA_PREVIEW_HTML_EOF
}
PREVIEW_HTML_FOOTER

cat >> "$tmp_file" <<'PREVIEW_CSS_HEADER'

# embedded document: preview/styles.css
_moma_preview_web_styles () {
    cat <<'MOMA_PREVIEW_CSS_EOF'
PREVIEW_CSS_HEADER
cat "$PREVIEW_CSS" >> "$tmp_file"
cat >> "$tmp_file" <<'PREVIEW_CSS_FOOTER'
MOMA_PREVIEW_CSS_EOF
}
PREVIEW_CSS_FOOTER

cat >> "$tmp_file" <<'PREVIEW_JS_HEADER'

# embedded document: preview/app.js
_moma_preview_web_script () {
    cat <<'MOMA_PREVIEW_JS_EOF'
PREVIEW_JS_HEADER
cat "$PREVIEW_JS" >> "$tmp_file"
cat >> "$tmp_file" <<'PREVIEW_JS_FOOTER'
MOMA_PREVIEW_JS_EOF
}
PREVIEW_JS_FOOTER

for module in "${modules[@]}"; do
    module_path="$MODULE_DIR/$module"
    if [[ ! -f "$module_path" ]]; then
        printf 'build: missing module: %s\n' "$module_path" >&2
        exit 1
    fi

    printf '\n# module: src/lib/%s\n' "$module" >> "$tmp_file"
    cat "$module_path" >> "$tmp_file"
done

cat >> "$tmp_file" <<'FOOTER'

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    _moma_main "$@"
fi
FOOTER

chmod 0755 "$tmp_file"
mv "$tmp_file" "$OUTPUT"
trap - EXIT

if [[ "$OUTPUT" == "$ROOT_DIR/dist/moma" ]]; then
    rm -f "$ROOT_DIR/moma.sh"
fi

printf 'Built %s\n' "$OUTPUT"
