#!/bin/bash
#
# Build the standalone Moma Bash library and CLI from its source modules.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${1:-$ROOT_DIR/dist/moma}"
OUTPUT_DIR="$(dirname "$OUTPUT")"
SOURCE_DIR="$ROOT_DIR/src"
HELP_MARKDOWN="$ROOT_DIR/docs/moma-help.md"
DOCS_MARKDOWN="$ROOT_DIR/docs/moma-docs.md"

modules=(
  core/version.sh
  core/errors.sh
  core/string.sh
  core/validation.sh
  core/config.sh
  core/color.sh
  core/semantic.sh
  core/terminal.sh
  core/registry.sh
  components/header.sh
  components/title.sh
  components/section-message.sh
  components/simple-list.sh
  components/box.sh
  components/resume.sh
  components/divider.sh
  components/label.sh
  components/input.sh
  components/prompt.sh
  components/select-common.sh
  components/single-select.sh
  components/single-select-groups.sh
  components/multi-select.sh
  components/multi-select-groups.sh
  components/rabbit.sh
  components/interaction.sh
  components/command-check.sh
  preview/web.sh
  preview/markdown.sh
  preview/main.sh
  cli/usage.sh
  cli/main.sh
)

if [[ ! -f "$HELP_MARKDOWN" ]]; then
  printf 'build: missing help document: %s\n' "$HELP_MARKDOWN" >&2
  exit 1
fi

if [[ ! -f "$DOCS_MARKDOWN" ]]; then
  printf 'build: missing docs document: %s\n' "$DOCS_MARKDOWN" >&2
  exit 1
fi

for module in "${modules[@]}"; do
  module_path="$SOURCE_DIR/$module"
  if [[ ! -f "$module_path" ]]; then
    printf 'build: missing module: %s\n' "$module_path" >&2
    exit 1
  fi
done

mkdir -p "$OUTPUT_DIR"
tmp_file="$(mktemp "$OUTPUT_DIR/.moma.XXXXXX")"
trap 'rm -f "$tmp_file"' EXIT

cat >"$tmp_file" <<'HEADER'
#!/bin/bash
#
# Generated by build.sh. Edit files in src instead of this file.
HEADER

# Each following stage appends one embedded asset to the same atomic artifact.
# shellcheck disable=SC2129
cat >>"$tmp_file" <<'HELP_HEADER'

# embedded document: docs/moma-help.md
_moma_help_markdown () {
    cat <<'MOMA_HELP_MARKDOWN_EOF'
HELP_HEADER
cat "$HELP_MARKDOWN" >>"$tmp_file"
cat >>"$tmp_file" <<'HELP_FOOTER'
MOMA_HELP_MARKDOWN_EOF
}
HELP_FOOTER

cat >>"$tmp_file" <<'PREVIEW_MD_HEADER'

# embedded document: docs/moma-docs.md
_moma_docs_markdown_document () {
    cat <<'MOMA_DOCS_MARKDOWN_EOF'
PREVIEW_MD_HEADER
cat "$DOCS_MARKDOWN" >>"$tmp_file"
cat >>"$tmp_file" <<'PREVIEW_MD_FOOTER'
MOMA_DOCS_MARKDOWN_EOF
}
PREVIEW_MD_FOOTER

for module in "${modules[@]}"; do
  module_path="$SOURCE_DIR/$module"
  printf '\n# module: src/%s\n' "$module" >>"$tmp_file"
  cat "$module_path" >>"$tmp_file"
done

cat >>"$tmp_file" <<'FOOTER'

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    _moma_main "$@"
fi
FOOTER

bash -n "$tmp_file"
chmod 0755 "$tmp_file"
mv "$tmp_file" "$OUTPUT"
trap - EXIT

if [[ "$OUTPUT" == "$ROOT_DIR/dist/moma" ]]; then
  rm -f "$ROOT_DIR/moma.sh"
fi

printf 'Built %s\n' "$OUTPUT"
