// Real terminal screenshots of the moma CLI, generated by
// `screenshots/generate.py` (see its README for how) and synced here from
// the repo's `.img/` folder. Every file is named `<api-entry-id>.png`, so a
// screenshot is looked up by id rather than declared per entry in
// apiEntries.ts - adding a new PNG here is enough to make it show up.
const modules = import.meta.glob<{ default: ImageMetadata }>(
  '../assets/screenshots/*.png',
  { eager: true }
);

const screenshotsById = new Map<string, ImageMetadata>(
  Object.entries(modules).map(([path, mod]) => {
    const id = path.slice(path.lastIndexOf('/') + 1).replace(/\.png$/, '');
    return [id, mod.default];
  })
);

export function getScreenshot(id: string): ImageMetadata | undefined {
  return screenshotsById.get(id);
}
